name: Deploy static site to Azure Web App - FaartmaalerV2Front

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Zip static files
        run: zip -r app.zip . -x ".git/*" -x ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FaartmaalerV2Front'
          slot-name: 'Production'
          package: ./app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_977F6E9F116A49C58FD1EEA681725FA4 }}
